name: ci 
on:
  push:
    branches:
      - master
  pull_request:
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created 

jobs:
  fe-checks:
    name: Frontend checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/datastax/pulsar-admin-console
      - name: Set up node
        uses: actions/setup-node@master
        with:
          node-version: '16'
          check-latest: true
      - name: Build vue components
        run: |
          cd dashboard
          npm ci
          npm install -g @vue/cli 
          npm run build

  be-checks:
    name: Backend checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/datastax/pulsar-admin-console
      - name: Set up node
        uses: actions/setup-node@master
        with:
          node-version: '16'
          check-latest: true
      - name: Run unit tests
        run: |
          cd server
          npm ci
          npm test

  docker:
    name: docker
    runs-on: ubuntu-latest 
    steps:
      - name: install podman
        run: |
          sudo apt-get -y install podman
          sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/datastax/pulsar-admin-console

      - name: Build Admin Console Docker Image
        run: |
          pwd
          podman manifest create adminconsole
          podman build --platform linux/amd64,linux/arm64 . --manifest adminconsole
